connections:
  mysql:
    host: 'localhost'
    port: 3306
    user: 'user'
    password: 'password'
    database: 'database'
    max_pool_size: 10
  redis:
    host: 'localhost'
    port: 6379
    timeout: 500
    password: ''